export const PROTOCOL_LIST = [
  "AC", "AMCOR", "AIRWELL", "AIRTON", "ARGO", "ARRIS", "BOSE", "BOSCH144",
  "CARRIER_AC", "CARRIER_AC40", "CARRIER_AC64", "CARRIER_AC84", "CARRIER_AC128",
  "CLIMABUTLER", "COOLIX", "COOLIX48", "CORONA_AC", "DAIKIN", "DAIKIN2", "DAIKIN64",
  "DAIKIN128", "DAIKIN152", "DAIKIN160", "DAIKIN176", "DAIKIN200", "DAIKIN216", "DAIKIN312",
  "DENON", "DELONGHI_AC", "DISH", "DOSHISHA", "ELECTRA_AC", "EPSON", "ECOCLIM",
  "ELITESCREENS", "GICABLE", "GLOBALCACHE", "GREE", "GOODWEATHER", "GORENJE",
  "HAIER_AC", "HAIER_AC160", "HAIER_AC176", "HAIER_AC_YRW02", "HITACHI_AC",
  "HITACHI_AC1", "HITACHI_AC2", "HITACHI_AC3", "HITACHI_AC264", "HITACHI_AC296",
  "HITACHI_AC344", "HITACHI_AC424", "INAX", "JVC", "KELON", "KELON168", "KELVINATOR",
  "LASERTAG", "LEGOPF", "LG", "LG2", "LUTRON", "MAGIQUEST", "MIDEA", "MIDEA24",
  "METZ", "MIRAGE", "MITSUBISHI", "MITSUBISHI2", "MITSUBISHI112", "MITSUBISHI136",
  "MITSUBISHI_AC", "MITSUBISHI_HEAVY_88", "MITSUBISHI_HEAVY_152", "MULTIBRACKETS",
  "MWM", "NEC", "NEC_LIKE", "NEOCLIMA", "NIKAI", "PANASONIC", "PANASONIC_AC",
  "PANASONIC_AC32", "PIONEER", "PRONTO", "RAW", "RC5", "RC5X", "RC6", "RCMM",
  "RHOSS", "SAMSUNG", "SAMSUNG36", "SAMSUNG_AC", "SANYO", "SANYO_AC", "SANYO_AC88",
  "SANYO_AC152", "SANYO_LC7461", "SAR", "SHARP", "SHARP_AC", "SHERWOOD", "SONY",
  "SONY_38K", "SYMPHONY", "TECHNIBEL_AC", "TECO", "TEKNOPOINT", "TCL96AC", "TCL112AC",
  "TOSHIBA_AC", "TOTO", "TRANSCOLD", "TRUMA", "TROTEC", "TROTEC_3550", "UNKNOWN",
  "UNUSED", "VESTEL_AC", "VOLTAS", "WHIRLPOOL_AC", "WHYNTER", "WOWWEE", "XMP",
  "YORK", "ZEPEAL"
]

export const MODE_LIST = ["自动", "制冷", "制热", "除湿", "送风"]
export const SPEED_LIST = ["自动", "低速", "中速", "强劲"]

// 首页顶部显示的设备名称（想改名只改这一行）
export const DEVICE_DISPLAY_NAME = 'ESP32空调控制器'

// Nordic UART Service（与 ESP32 固件保持一致）
export const BLE_CONFIG = {
  serviceUUID: '6E400001-B5A3-F393-E0A9-E50E24DCCA9E',
  rxCharUUID: '6E400002-B5A3-F393-E0A9-E50E24DCCA9E',
  txCharUUID: '6E400003-B5A3-F393-E0A9-E50E24DCCA9E'
}
